# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.

include: ['_pages']

title: Disinfo
baseurl: ""
url: https://disinfo.quaidorsay.fr

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: _pages/en
    values:
      lang: en
  -
    scope:
      path: _pages/fr
    values:
      lang: fr

exclude:
  - README.md
  - .circleci
  - vendor
  - assets/js/cgus/node_modules

kramdown:
  toc_levels: 2..5

plugins:
  - jekyll-redirect-from
