# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.

include: ['_pages']

title: Disencyclopedia
baseurl: ""
url: https://disinfo.quaidorsay.fr

search_enabled: true

defaults:
  -
    scope:
      path: "" # means "all files"
    values:
      nav_exclude: true
      numbered_headers: false
      search_exclude: true
  -
    scope:
      path: _pages/en/encyclopedia
    values:
      layout: encyclopedia
      nav_exclude: false
      numbered_headers: true
      search_exclude: false

exclude:
  - README.md
  - README-fr.md
  - .circleci
  - vendor

kramdown:
  toc_levels: 2..4
